---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
squash: false
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Crafty Controller"
  org.opencontainers.image.description: "A Minecraft Server Management Panel for Home Assistant"
  org.opencontainers.image.source: "https://github.com/YOUR_USERNAME/addon-crafty-controller"
  org.opencontainers.image.licenses: "MIT"
args:
  CRAFTY_VERSION: "4.4.7"
