---
build_from:
  amd64: registry.gitlab.com/crafty-controller/crafty-4:latest
squash: false
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Crafty Controller"
  org.opencontainers.image.description: "A Minecraft Server Management Panel for Home Assistant"
  org.opencontainers.image.source: "https://github.com/elysiandc/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
