# Created with assistance from chatGPT and Claude
name: Crafty Controller
version: "1.0.0"
slug: crafty-controller
description: A Home Assistant add-on for Crafty Controller, a Minecraft server management panel.
url: "https://github.com/elysiandc/hassio-addons"
webui: "https://[HOST]:[PORT:8443]"
panel_icon: mdi:server
panel_title: Crafty

arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
#host_network: true
homeassistant_api: false
#environment: { "PYTHONUNBUFFERED": "1" }

# Enable Ingress
ingress: true
ingress_port: 8433
ingress_entry: "/panel/login"
ingress_stream: true # Needed for HTTPS / WS connections in iframe

# Required for Docker access, server port ranges, and file persistence
#privileged:
#  - SYS_ADMIN

# Port mappings
ports:
  8433/tcp: 8443 # HTTPS WebUI
  8100/tcp: 8100 # Dynmap (optional)
  8023/tcp: 8023 # BlueMap (optional)
  19132/udp: 19132 # Bedrock
  19134/udp: 19134 #Geyser/Floodgate Port for Bedrock Clients
  25500/tcp: 25500
  25565/tcp: 25565
  25566/tcp: 25566
  25567/tcp: 25567
  25568/tcp: 25568
  25569/tcp: 25569
  25570/tcp: 25570

ports_description:
  8433/tcp: 8443 "HTTPS Web interface"
  8100/tcp: 8100 "Dynmap (optional)"
  8023/tcp: 8023 "BlueMap (optional)"
  19132/udp: 19132 "Bedrock"
  19134/udp: 19134 "Geyser/Floodgate Port for Bedrock Clients"
  25500/tcp: 25500 "Extra port"
  25565/tcp: 25565 "Minecraft server port"
  25566/tcp: "Additional Minecraft server port"
  25567/tcp: "Additional Minecraft server port"
  25568/tcp: "Additional Minecraft server port"
  25569/tcp: "Additional Minecraft server port"
  25570/tcp: "Additional Minecraft server port"

map:
  - addon_config:rw
  - ssl:rw
  - addons:rw
  #- backup:rw
  - share:rw
  #- data:rw

options:
  username: admin
  password: ChangeMePassword123!
  ssl: true
  force_https: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: debug
  #use_cdn: false
  #use_uvloop: true
  #dev_mode: false

schema:
  username: str
  password: "str(12,72)?" # Min 12 chars, max 72
  ssl: bool
  force_https: bool
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)#
  #use_cdn: bool
  #use_uvloop: bool
  #dev_mode: bool

environment:
  LOG_FORMAT: '"{LEVEL}: {MESSAGE}"'
