# Created with assistance from chatGPT
name: Crafty Controller
version: "1.0.0"
slug: crafty-controller
description: A Home Assistant add-on for Crafty Controller, a game server management panel.
arch:
  - amd64
#  - aarch64
#  - armv7
startup: application
boot: auto
init: false
host_network: true
homeassistant_api: false
environment: { "PYTHONUNBUFFERED": "1" }

# Enable Ingress
ingress: true
ingress_port: 8000
ingress_entry: /
# Needed for HTTPS / WS connections in iframe
ingress_stream: true

# Crafty does not require auth cookie passthrough
panel_icon: mdi:server
panel_title: Crafty

# Required for Docker access, server port ranges, and file persistence
privileged:
  - SYS_ADMIN

# Port mappings
ports:
  8000/tcp: 8000 # HTTP WebUI
  8443/tcp: 8443 # HTTPS WebUI
  8100/tcp: 8100 # BlueMap (optional)
  19132/udp: 19132 # Bedrock
  19134/udp: 19134 #Geyser/Floodgate Port for Bedrock Clients
  25500/tcp: 25500

map:
  - /share/crafty:/crafty
  - /config/crafty/app/config:/crafty/app/config
  - /backup:/crafty/backups
  - /share/crafty/logs:/crafty/logs
  - /share/crafty/servers:/crafty/servers
  - /share/crafty/import:/crafty/import

options: {}
schema: {}
