# Created with assistance from chatGPT and Claude
name: Crafty Controller
version: "1.0.0"
slug: crafty-controller
description: A Home Assistant add-on for Crafty Controller, a Minecraft server management panel.
url: "https://github.com/elysiandc/hassio-addons"
webui: "https://[HOST]:[PORT:8433]"
panel_icon: mdi:server
panel_title: Crafty

arch:
  - amd64
startup: application
boot: auto
init: false
s6-overlay: false
host_network: true
homeassistant_api: false
#environment: { "PYTHONUNBUFFERED": "1" }
backup: cold

# Enable Ingress
ingress: true
ingress_port: 8433
ingress_entry: "/panel/login"
ingress_stream: true # Needed for HTTPS / WS connections in iframe

# Required for Docker access, server port ranges, and file persistence
#privileged:
#  - SYS_ADMIN

# Port mappings
ports:
  8443/tcp: 8433 # HTTPS WebUI
  8123/tcp: 8022 # Dynmap (optional)
  8023/tcp: 8023 # BlueMap (optional)
  19132/udp: 19132 # Bedrock
  19134/udp: 19134 #Geyser/Floodgate Port for Bedrock Clients
  25500/tcp: 25500
  25565/tcp: 25565
  25566/tcp: 25566
  25567/tcp: 25567
  25568/tcp: 25568
  25569/tcp: 25569
  25570/tcp: 25570

ports_description:
  8443/tcp: 8433 "HTTPS Web interface"
  8123/tcp: 8022 "Dynmap (optional)"
  8023/tcp: 8023 "BlueMap (optional)"
  19132/udp: 19132 "Bedrock"
  19134/udp: 19134 "Geyser/Floodgate Port for Bedrock Clients"
  25500/tcp: 25500 "Extra port"
  25565/tcp: 25565 "Minecraft server port"
  25566/tcp: "Additional Minecraft server port"
  25567/tcp: "Additional Minecraft server port"
  25568/tcp: "Additional Minecraft server port"
  25569/tcp: "Additional Minecraft server port"
  25570/tcp: "Additional Minecraft server port"

map:
  - type: share
    read_only: false
  - type: ssl
  - type: backup
  - type: addon_config
    path: /crafty/app/config
    read_only: false

options:
  username: "admin"
  password: null
  log_level: "info"

schema:
  username: str
  password: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)

environment:
  LOG_FORMAT: '"{LEVEL}: {MESSAGE}"'
